# Generated by Django 2.2.4 on 2020-07-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=None, max_length=255, verbose_name='Unique Code'),
        ),
    ]
