# Generated by Django 2.2.4 on 2020-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200711_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.IntegerField(default=0, verbose_name='Days Left')),
            ],
        ),
    ]
