# Generated by Django 2.2.4 on 2020-07-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_language_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='text',
            field=models.CharField(default='', max_length=255, verbose_name='Text'),
        ),
    ]
