# Generated by Django 2.2.4 on 2020-07-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200712_1647'),
        ('core', '0007_auto_20200712_1652'),
    ]

    operations = [
    ]
