# Generated by Django 2.2.4 on 2020-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cartbase_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbase',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
    ]
