# Generated by Django 2.2.4 on 2020-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderbase_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
    ]
