# Generated by Django 2.2.4 on 2020-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200722_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='Unique Code'),
        ),
    ]
