# Generated by Django 2.2.4 on 2020-07-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchbase',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='Unique Code'),
        ),
        migrations.AddField(
            model_name='branchbase',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_language', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=None, max_length=255, verbose_name='Unique Code'),
        ),
    ]
