# Generated by Django 2.2.4 on 2020-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200723_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtitle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
