# Generated by Django 2.2.4 on 2022-01-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220124_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.IntegerField(default=0, verbose_name='External ID'),
        ),
    ]
