# Generated by Django 2.2.4 on 2022-01-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='External ID'),
        ),
    ]
