# Generated by Django 2.2.4 on 2022-01-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220124_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchbase',
            name='title',
        ),
        migrations.AddField(
            model_name='branchbase',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
