# Generated by Django 2.2.4 on 2020-07-11 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0, verbose_name='Chat id')),
                ('first_name', models.CharField(default=None, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Username')),
                ('phone', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Phone')),
                ('language_set', models.BooleanField(blank=True, default=False, null=True, verbose_name='Language set')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_language', to='core.Language')),
            ],
        ),
    ]
