# Generated by Django 2.2.4 on 2020-07-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartbase'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='PaySystem Number')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CartBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.User')),
            ],
            bases=('core.cartbase',),
        ),
    ]
