# Generated by Django 2.2.4 on 2020-07-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200711_2344'),
        ('telegram', '0003_auto_20200711_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('settings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Settings')),
                ('managers', models.ManyToManyField(null=True, to='telegram.User')),
            ],
            bases=('core.settings',),
        ),
    ]
