# Generated by Django 2.2.4 on 2020-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='managers',
            field=models.ManyToManyField(blank=True, to='telegram.User'),
        ),
    ]
