# Generated by Django 2.2.4 on 2020-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_auto_20200716_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysystem',
            name='token',
            field=models.CharField(default='', max_length=1024, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
