# Generated by Django 2.2.4 on 2020-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_paysystem_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysystem',
            name='currency',
            field=models.CharField(default='', max_length=10, verbose_name='Currency'),
        ),
    ]
