# Generated by Django 2.2.4 on 2020-07-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderbase_orderstatus'),
        ('telegram', '0010_paysystem_eq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.OrderBase')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.User')),
            ],
            bases=('core.orderbase',),
        ),
    ]
