# Generated by Django 2.2.4 on 2020-07-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paysystem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paysystem_telegram_order', to='telegram.PaySystem'),
            preserve_default=False,
        ),
    ]
