# Generated by Django 2.2.4 on 2020-07-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0015_branch_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default="", verbose_name='Posible Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_telegram_order', to='telegram.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_branch_telegram_order', to='telegram.Branch'),
        ),
    ]
