# Generated by Django 2.2.4 on 2022-01-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0016_auto_20200722_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created at'),
        ),
    ]
