# Generated by Django 2.2.4 on 2022-01-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0017_auto_20220123_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='external_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='External ID'),
        ),
    ]
