# Generated by Django 2.2.4 on 2022-01-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0018_branch_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
