# Generated by Django 2.2.4 on 2020-07-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200723_1808'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='web_message_language', to='core.Language'),
            preserve_default=False,
        ),
    ]
